apiVersion: v2
name: my-traefik
description: A Helm chart for Kubernetes

type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: cert-manager
    alias: certmanager
    repository: https://charts.jetstack.io
    version: 1.16.2
    condition: config.https.enabled
  - name: traefik
    repository: https://helm.traefik.io/traefik
    version: 33.1.0