apiVersion: v2
name: my-traefik
description: A Helm chart for Kubernetes

type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: cert-manager
    alias: certmanager
    repository: https://charts.jetstack.io
    # save the crds/cert-manager.crds.yaml at the same time
    # https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.crds.yaml
    version: 1.16.2
    condition: config.https.enabled
  - name: traefik
    repository: https://helm.traefik.io/traefik
    version: 33.1.0