{{- if eq .Values.config.auth.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: traefik-auth-users
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.config.auth.username }}
  password: {{ .Values.config.auth.password }}
{{- end }}


{{- if eq .Values.config.https.enabled true }}
---  
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: "{{ .Values.config.https.cloudflareApiToken }}"
{{- end }}